using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using Slate.Tokens.Emitters;
using Slate.Tokens.Loading;
using Slate.Tokens.Model;

namespace Slate.Tokens;

/// <summary>The shared icon set (design/icons/icons.json): name → stroke path data on a square viewBox.</summary>
public sealed partial record IconSet(double ViewBox, double StrokeWidth, IReadOnlyList<(string Name, string Path)> Icons)
{
    public static IconSet Empty { get; } = new(24, 2, []);

    // Explicit commands only, exact argument counts, single-space separated numbers:
    // parses identically in SVG, WPF and Avalonia (no implicit line-tos, commas or packed negatives).
    private static readonly IReadOnlyDictionary<char, int> Arity = new Dictionary<char, int>
    {
        ['M'] = 2, ['L'] = 2, ['T'] = 2, ['H'] = 1, ['V'] = 1, ['S'] = 4, ['Q'] = 4, ['C'] = 6, ['A'] = 7, ['Z'] = 0,
    };

    [GeneratedRegex(@"^-?\d+(?:\.\d+)?$")]
    private static partial Regex NumberPattern();

    internal static bool IsStrictPath(string path)
    {
        if (string.IsNullOrEmpty(path) || path[0] != 'M')
            return false;

        var parts = path.Split(' ');
        var i = 0;
        while (i < parts.Length)
        {
            var head = parts[i];
            if (head.Length == 0 || !Arity.TryGetValue(head[0], out var count))
                return false;

            // The first number is glued to the command letter ("M20"); Z stands alone.
            var args = new List<string>();
            if (head.Length > 1) args.Add(head[1..]);
            else if (count > 0) return false;
            i++;
            while (args.Count < count && i < parts.Length) args.Add(parts[i++]);

            if (args.Count != count || !args.All(a => NumberPattern().IsMatch(a)))
                return false;
        }
        return true;
    }

    [GeneratedRegex("^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$")]
    private static partial Regex KebabName();

    public static IconSet Load(string file)
    {
        var root = JsonNode.Parse(File.ReadAllText(file), documentOptions: new JsonDocumentOptions { CommentHandling = JsonCommentHandling.Skip })
                   ?? throw new TokenException($"{file} is empty.");
        var icons = root["icons"]?.AsObject() ?? throw new TokenException($"{file} has no 'icons' object.");
        return Create(
            root["viewBox"]?.GetValue<double>() ?? 24,
            root["strokeWidth"]?.GetValue<double>() ?? 2,
            icons.Select(kv => (kv.Key, kv.Value?.GetValue<string>() ?? "")).ToList());
    }

    public static IconSet Create(double viewBox, double strokeWidth, IReadOnlyList<(string Name, string Path)> icons)
    {
        foreach (var (name, path) in icons)
        {
            if (!KebabName().IsMatch(name))
                throw new TokenException($"Icon name '{name}' must be kebab-case.", $"icons.{name}");
            if (!IsStrictPath(path))
                throw new TokenException("Path data must use explicit upper-case commands and space-separated numbers.", $"icons.{name}");
        }

        var dupes = icons.GroupBy(i => i.Name).Where(g => g.Count() > 1).Select(g => g.Key).ToList();
        if (dupes.Count > 0)
            throw new TokenException($"Duplicate icon(s): {string.Join(", ", dupes)}.");

        return new IconSet(viewBox, strokeWidth, icons);
    }
}

/// <summary>icons.ts for the web package: a typed record of path data.</summary>
public sealed class IconTypeScriptEmitter : IEmitter
{
    public string Name => "icons-ts";

    public IReadOnlyList<GeneratedFile> Emit(TokenBuild build)
    {
        var w = new Writer();
        w.Line($"// {EmitterRegistry.Banner}").Line()
         .Line($"export const iconViewBox = {Format.Number(build.Icons.ViewBox)};")
         .Line($"export const iconStrokeWidth = {Format.Number(build.Icons.StrokeWidth)};").Line()
         .Line("export const icons = {").Indent();
        foreach (var (name, path) in build.Icons.Icons)
            w.Line($"{JsonSerializer.Serialize(name)}: {JsonSerializer.Serialize(path)},");
        w.Outdent().Line("} as const;").Line()
         .Line("export type IconName = keyof typeof icons;");
        return [new GeneratedFile("icons.ts", w.ToString())];
    }
}

/// <summary>SlateIcons.g.cs for .NET platforms (Blazor renders SVG; WPF/Avalonia parse the data as Geometry).</summary>
public sealed class IconCSharpEmitter : IEmitter
{
    public string Name => "icons-cs";

    public IReadOnlyList<GeneratedFile> Emit(TokenBuild build)
    {
        var w = new Writer();
        w.Line($"// <auto-generated>{EmitterRegistry.Banner}</auto-generated>")
         .Line("#nullable enable").Line()
         .Line("namespace Slate;").Line()
         .Line("/// <summary>Built-in stroke icons (24px viewBox, 2px round strokes). Values are path data.</summary>")
         .Line("public static partial class SlateIcons")
         .Line("{").Indent()
         .Line($"public const double ViewBox = {Format.Number(build.Icons.ViewBox)};")
         .Line($"public const double StrokeWidth = {Format.Number(build.Icons.StrokeWidth)};").Line();

        foreach (var (name, path) in build.Icons.Icons)
            w.Line($"public const string {string.Concat(name.Split('-').Select(Naming.Pascal))} = {JsonSerializer.Serialize(path)};");

        w.Line().Line("/// <summary>All icons by kebab-case name.</summary>")
         .Line("public static readonly IReadOnlyDictionary<string, string> All = new Dictionary<string, string>").Line("{").Indent();
        foreach (var (name, _) in build.Icons.Icons)
            w.Line($"[{JsonSerializer.Serialize(name)}] = {string.Concat(name.Split('-').Select(Naming.Pascal))},");
        w.Outdent().Line("};");

        w.Outdent().Line("}");
        return [new GeneratedFile("SlateIcons.g.cs", w.ToString())];
    }
}
