<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <IsPackable>false</IsPackable>
    <ApplicationManifest Condition="Exists('app.manifest')">app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Slate.Avalonia\Slate.Avalonia.csproj" />
  </ItemGroup>
</Project>
