using System.Text.Json;
using System.Text.Json.Nodes;
using Slate.Tokens.Loading;
using Slate.Tokens.Model;

namespace Slate.Tokens.Emitters;

/// <summary>
/// SlateTokens.g.cs — strongly typed constants for .NET code (Slate.Core and anything built on it).
/// Shared tokens live at the top level; themed tokens under SlateTokens.Themes.{Name}.
/// Colours are CSS-order hex strings (#RRGGBB or #RRGGBBAA); dimensions are pixels; durations are milliseconds.
/// </summary>
public sealed class CSharpEmitter : IEmitter
{
    public string Name => "csharp";

    public string Namespace { get; init; } = "Slate";

    public IReadOnlyList<GeneratedFile> Emit(TokenBuild build)
    {
        var w = new Writer();
        w.Line($"// <auto-generated>{EmitterRegistry.Banner}</auto-generated>")
         .Line("#nullable enable")
         .Line()
         .Line($"namespace {Namespace};")
         .Line()
         .Line("/// <summary>Alloy design tokens. Colours: CSS hex (#RRGGBB[AA]); sizes: px; durations: ms.</summary>")
         .Line("public static partial class SlateTokens")
         .Line("{").Indent();

        WriteTree(w, build.Shared);

        w.Line()
         .Line("/// <summary>Theme names, in source order.</summary>")
         .Line($"public static readonly IReadOnlyList<string> ThemeNames = new[] {{ {string.Join(", ", build.Themes.Select(t => $"\"{t.Name}\""))} }};")
         .Line()
         .Line("public static class Themes")
         .Line("{").Indent();
        foreach (var theme in build.Themes)
        {
            w.Line($"public static class {Naming.CSharpIdentifier(theme.Name)}").Line("{").Indent();
            WriteTree(w, theme.Tokens);
            w.Outdent().Line("}");
        }
        w.Outdent().Line("}");

        w.Outdent().Line("}");
        return [new GeneratedFile("SlateTokens.g.cs", w.ToString())];
    }

    private sealed class Node
    {
        public readonly SortedDictionary<string, Node> Groups = new(StringComparer.Ordinal);
        public readonly List<(string Name, Token Token)> Leaves = [];
    }

    private static void WriteTree(Writer w, IEnumerable<Token> tokens)
    {
        var root = new Node();
        foreach (var t in tokens)
        {
            var node = root;
            foreach (var seg in t.Segments[..^1])
            {
                var id = Naming.CSharpIdentifier(seg);
                if (!node.Groups.TryGetValue(id, out var child))
                    node.Groups[id] = child = new Node();
                node = child;
            }
            node.Leaves.Add((Naming.CSharpIdentifier(t.Segments[^1]), t));
        }

        WriteNode(w, root, enclosing: null);
    }

    private static void WriteNode(Writer w, Node node, string? enclosing)
    {
        foreach (var (name, token) in node.Leaves)
        {
            var id = name == enclosing ? name + "Value" : name;
            if (token.Description is { } d)
                w.Line($"/// <summary>{System.Security.SecurityElement.Escape(d)}</summary>");
            w.Line(Member(id, token));
        }

        foreach (var (name, child) in node.Groups)
        {
            w.Line($"public static class {name}").Line("{").Indent();
            WriteNode(w, child, name);
            w.Outdent().Line("}");
        }
    }

    private static string Member(string id, Token t) => t.Value switch
    {
        ColorValue c => $"public const string {id} = \"{c.ToCssHex()}\";",
        DimensionValue { IsPixels: true } d => $"public const double {id} = {Format.Number(d.Value)};",
        DimensionValue d => $"public const string {id} = \"{d}\";",
        DurationValue d => $"public const double {id} = {Format.Number(d.Milliseconds)}; // ms",
        CubicBezierValue b => $"public static readonly double[] {id} = {{ {Format.Number(b.X1)}, {Format.Number(b.Y1)}, {Format.Number(b.X2)}, {Format.Number(b.Y2)} }};",
        FontFamilyValue f => $"public const string {id} = {Literal(f.ToString())};",
        ShadowValue s => $"public const string {id} = {Literal(s.ToCss())}; // CSS box-shadow syntax",
        TypographyValue v => $"public static readonly SlateTextStyle {id} = new({Literal(v.FontFamily.ToString())}, {Format.Number(v.FontSize.Value)}, {Format.Number(v.FontWeight)}, {Format.Number(v.LineHeight)}, {Format.Number(v.LetterSpacing.Unit == "em" ? v.LetterSpacing.Value : 0)});",
        double n => $"public const double {id} = {Format.Number(n)};",
        _ => throw new TokenException($"No C# mapping for {t.Type}.", t.Path),
    };

    private static string Literal(string s) => JsonSerializer.Serialize(s);
}

/// <summary>
/// tokens.resolved.json — every token with its final value, for documentation sites, design tools and tests
/// in any language. Values use CSS syntax.
/// </summary>
public sealed class ResolvedJsonEmitter : IEmitter
{
    public string Name => "json";

    public IReadOnlyList<GeneratedFile> Emit(TokenBuild build)
    {
        var root = new JsonObject
        {
            ["$comment"] = EmitterRegistry.Banner,
            ["prefix"] = build.Prefix,
            ["defaultTheme"] = build.Config.DefaultTheme,
            ["shared"] = Section(build, build.Shared),
            ["themes"] = new JsonObject(build.Themes.Select(t =>
                new KeyValuePair<string, JsonNode?>(t.Name, Section(build, t.Tokens)))),
        };

        var json = root.ToJsonString(new JsonSerializerOptions { WriteIndented = true, Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping });
        return [new GeneratedFile("tokens.resolved.json", json.Replace("\r\n", "\n") + "\n")];
    }

    private static JsonObject Section(TokenBuild build, IEnumerable<Token> tokens) => new(tokens.Select(t =>
    {
        var entry = new JsonObject
        {
            ["type"] = t.Type.ToString(),
            ["cssVar"] = Naming.CssVariable(build.Prefix, t.Path),
            ["xamlKey"] = Naming.XamlKey(build.Prefix, t.Path),
            ["value"] = t.Value is TypographyValue v
                ? new JsonObject
                {
                    ["fontFamily"] = v.FontFamily.ToCss(),
                    ["fontSize"] = v.FontSize.ToString(),
                    ["fontWeight"] = v.FontWeight,
                    ["lineHeight"] = v.LineHeight,
                    ["letterSpacing"] = v.LetterSpacing.ToString(),
                }
                : CssEmitter.Value(t),
        };
        if (t.Description is { } d)
            entry["description"] = d;
        return new KeyValuePair<string, JsonNode?>(t.Path, entry);
    }));
}
