using System.Text;
using Slate.Tokens.Loading;

namespace Slate.Tokens.Emitters;

/// <summary>A file produced by an emitter, relative to that emitter's output directory.</summary>
public sealed record GeneratedFile(string RelativePath, string Content);

public interface IEmitter
{
    /// <summary>Key used in the config's "outputs" map.</summary>
    string Name { get; }

    IReadOnlyList<GeneratedFile> Emit(TokenBuild build);
}

public static class EmitterRegistry
{
    public static IReadOnlyList<IEmitter> All { get; } =
    [
        new CssEmitter(),
        new WpfXamlEmitter(),
        new AvaloniaXamlEmitter(),
        new CSharpEmitter(),
        new ResolvedJsonEmitter(),
        new IconTypeScriptEmitter(),
        new IconCSharpEmitter(),
    ];

    public const string Banner = "Generated by Slate.Tokens from design/tokens. Do not edit — run `dotnet run --project tools/Slate.Tokens.Cli -- build`.";
}

/// <summary>StringBuilder with indentation and \n line endings on every OS (keeps generated files diff-stable).</summary>
internal sealed class Writer
{
    private readonly StringBuilder _sb = new();
    private int _indent;

    public Writer Line(string text = "")
    {
        if (text.Length > 0)
            _sb.Append(' ', _indent * 2).Append(text);
        _sb.Append('\n');
        return this;
    }

    public Writer Indent() { _indent++; return this; }
    public Writer Outdent() { _indent--; return this; }

    public override string ToString() => _sb.ToString();
}
